name: Daily Github-Trending

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.14.0

      - name: Install dependencies
        run: |
          npm install

      - name: Run Scraper
        run: |
          npm run scraper

      # Runs a set of commands using the runners shell
      - name: push to origin master
        run: |
          echo start push
          git config --global user.name "JackEasons"
          git config --global user.email "yixiaowu2008@gmail.com"

          git add -A
          git commit -m $(date '+%Y-%m-%d')
          git push
