# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Daily Github-Trending

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install

      - name: Run Scraper
        run: |
          npm run scraper

      # Runs a set of commands using the runners shell
      - name: push to origin master
        run: |
          echo start push
          git config --global user.name "lxfriday"
          git config --global user.email "liu3248184446@outlook.com"

          git add -A
          git commit -m $(date '+%Y-%m-%d')
          git push
